apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-cluster-admin
  labels:
    app: eventstreams
rules:
  - apiGroups:
      - eventstreams.ibm.com
    resources:
      - eventstreams
      - eventstreams/status
      - kafkatopics
      - kafkatopics/status
      - kafkauser
      - kafkauser/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete