###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2019  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
###############################################################################
############################# IBM EVENT STREAMS ###############################
###############################################################################

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: false

logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local

tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: beta.kubernetes.io/arch
              operator: In
              values:
                - amd64
nodeSelector: {}

imagePullSecrets: ibm-entitlement-key

operatorIndex:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: operator-index
    tag: 2020-05-27-20.18.23-dddcbaf

operatorBundle:
    image:
      repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
      name: operator-bundle
      tag: 2020-05-27-20.18.23-dddcbaf

operator:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/operator
    tag: 2020-05-28-17.28.20-5b564bb-exp
operatorInit:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/operator-init
    tag: 2020-05-28-17.28.20-5b564bb-exp


restProducer:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-rest-producer-v2-icp-linux
    tag: 2020-05-28-13.50.41-6e8642c
adminApi:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-admin-icp-linux
    tag: 2020-05-28-13.50.41-6e8642c
schemaRegistry:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-schema-registry-icp-linux
    tag: 2020-05-28-16.03.46-a2ca6bf-dev
schemaRegistryAvro:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-schema-registry-avro-icp-linux
    tag: 2020-05-28-15.51.55-078165d-dev
schemaRegistryProxy:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-schema-proxy-icp-linux
    tag: 2020-05-28-13.50.36-6e8642c
adminUi:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-admin-ui-icp-linux
    tag: 2020-05-28-17.47.10-6cb6188-dev
adminUiDatabase:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-session-store-icp-linux
    tag: 2020-04-09-15.40.36-f32e234
collector:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: eventstreams-metrics-collector-icp-linux
    tag: 2020-05-28-16.23.09-8cee6ad


zookeeper:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
kafka:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
kafkaConnect:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
kafkaConnects2i:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
cruiseControl:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
topicOperator:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/operator
    tag: 2020-05-28-17.28.20-5b564bb-exp
userOperator:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/operator
    tag: 2020-05-28-17.28.20-5b564bb-exp
kafkaInit:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/operator
    tag: 2020-05-28-17.28.20-5b564bb-exp
tlsSidecarZookeeper:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
tlsSidecarKafka:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
tlsSidecarEntityOperator:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
tlsSidecarCruiseControl:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
kafkaMirrorMaker:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
kafkaExporter:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
jmxTrans:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/jmxtrans
    tag: 2020-05-28-17.28.20-5b564bb-exp
kafkaMirrorMaker2:
  image:
    repository: hyc-qp-stable-docker-local.artifactory.swg-devops.com
    name: strimzi/kafka
    tagPrefix: 2020-05-28-17.28.20-5b564bb-exp
resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 1Gi
    cpu: 200m
livenessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
readinessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5

createGlobalResources: true
