scorecard:
  output: text
  namespace: es
  plugins:
    - basic:
        cr-manifest:
          - "examples/eventstreams/eventstreams-quickstart.yaml"
        csv-path: "deploy/olm-catalog/ibm-eventstreams-operator/2020.2.1/ibm-eventstreams-operator.v2020.2.1.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "examples/eventstreams/eventstreams-quickstart.yaml"
        csv-path: "deploy/olm-catalog/ibm-eventstreams-operator/2020.2.1/ibm-eventstreams-operator.v2020.2.1.clusterserviceversion.yaml"
