###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2019  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventstreams-operator
  labels:
    app: {{ template "eventstreams.name" . }}
    chart: {{ template "eventstreams.chart" . }}
    component: eventstreams-operator-role-binding
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: eventstreams-cluster-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: eventstreams-operator
  apiGroup: rbac.authorization.k8s.io
