###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: {{ template "eventstreams.name" . }}
    chart: {{ template "eventstreams.chart" . }}
    component: deployment
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: eventstreams-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: eventstreams-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eventstreams-cluster-operator
      eventstreams.ibm.com/kind: cluster-operator
  template:
    metadata:
      annotations:
        productID: "2cba508800504d0abfa48a0e2c4ecbe2"
        productName: "IBM Event Streams"
        productVersion: "10.0.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: ""
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        name: eventstreams-cluster-operator
        eventstreams.ibm.com/kind: cluster-operator
        app: eventstreams
        app.kubernetes.io/instance: eventstreams-operator
        app.kubernetes.io/managed-by: olm
        app.kubernetes.io/name: eventstreams-operator
    spec:
      serviceAccountName: eventstreams-cluster-operator
      initContainers:
      - name: init
        image: {{ default .Values.operatorInit.image.repository .Values.imageRepositoryOverride }}/{{ .Values.operatorInit.image.name }}@sha256:{{ .Values.operatorInit.image.digest }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        env:
          - name: EVENTSTREAMS_OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: EVENTSTREAMS_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      containers:
        - name: eventstreams-cluster-operator
          image: {{ default .Values.operator.image.repository .Values.imageRepositoryOverride }}/{{ .Values.operator.image.name }}@sha256:{{ .Values.operator.image.digest }}
          args:
          - /opt/strimzi/bin/eventstreams_cluster_operator_run.sh
          env:
            - name: WATCHED_NAMESPACE
              {{- if .Values.watchAnyNamespace }}
              value: "*"
              {{- else }}
              {{- if .Values.watchNamespaces -}}
              {{- $ns := .Values.watchNamespaces -}}
              {{- $ns := append $ns .Release.Namespace }}
              value: "{{ join "," $ns }}"
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
              {{- end }}
              {{- end }}
            - name: EVENTSTREAMS_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EVENTSTREAMS_IMAGE_PULL_POLICY
              value: IfNotPresent
            - name: EVENTSTREAMS_FULL_RECONCILIATION_INTERVAL_MS
              value: {{ .Values.fullReconciliationIntervalMs | quote }}
            - name: EVENTSTREAMS_OPERATION_TIMEOUT_MS
              value: {{ .Values.operationTimeoutMs | quote }}
            {{- if .Values.imagePullSecrets }}
            - name: EVENTSTREAMS_IMAGE_PULL_SECRETS
              value: {{ .Values.imagePullSecrets }}
            {{- end }}
            - name: EVENTSTREAMS_LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # Core images
            {{ template "strimzi.kafka.image.map" . }}
            - name: EVENTSTREAMS_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: "{{ default .Values.topicOperator.image.repository .Values.imageRepositoryOverride }}/{{ .Values.topicOperator.image.name }}@sha256:{{ .Values.topicOperator.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_USER_OPERATOR_IMAGE
              value: "{{ default .Values.userOperator.image.repository .Values.imageRepositoryOverride }}/{{ .Values.userOperator.image.name }}@sha256:{{ .Values.userOperator.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_KAFKA_INIT_IMAGE
              value: "{{ default .Values.kafkaInit.image.repository .Values.imageRepositoryOverride }}/{{ .Values.kafkaInit.image.name }}@sha256:{{ .Values.kafkaInit.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_JMXTRANS_IMAGE
              value: "{{ default .Values.jmxTrans.image.repository .Values.imageRepositoryOverride }}/{{ .Values.jmxTrans.image.name }}@sha256:{{ .Values.jmxTrans.image.digest }}"
            # Proprietary images
            - name: EVENTSTREAMS_DEFAULT_REST_PRODUCER_IMAGE
              value: "{{ default .Values.restProducer.image.repository .Values.imageRepositoryOverride }}/{{ .Values.restProducer.image.name }}@sha256:{{ .Values.restProducer.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_ADMIN_API_IMAGE
              value: "{{ default .Values.adminApi.image.repository .Values.imageRepositoryOverride }}/{{ .Values.adminApi.image.name }}@sha256:{{ .Values.adminApi.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_IMAGE
              value: "{{ default .Values.schemaRegistry.image.repository .Values.imageRepositoryOverride }}/{{ .Values.schemaRegistry.image.name }}@sha256:{{ .Values.schemaRegistry.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_AVRO_IMAGE
              value: "{{ default .Values.schemaRegistryAvro.image.repository .Values.imageRepositoryOverride }}/{{ .Values.schemaRegistryAvro.image.name }}@sha256:{{ .Values.schemaRegistryAvro.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_PROXY_IMAGE
              value: "{{ default .Values.schemaRegistryProxy.image.repository .Values.imageRepositoryOverride }}/{{ .Values.schemaRegistryProxy.image.name }}@sha256:{{ .Values.schemaRegistryProxy.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_IMAGE
              value: "{{ default .Values.adminUi.image.repository .Values.imageRepositoryOverride }}/{{ .Values.adminUi.image.name }}@sha256:{{ .Values.adminUi.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_REDIS_IMAGE
              value: "{{ default .Values.adminUiDatabase.image.repository .Values.imageRepositoryOverride }}/{{ .Values.adminUiDatabase.image.name }}@sha256:{{ .Values.adminUiDatabase.image.digest }}"
            - name: EVENTSTREAMS_DEFAULT_COLLECTOR_IMAGE
              value: "{{ default .Values.collector.image.repository .Values.imageRepositoryOverride }}/{{ .Values.collector.image.name }}@sha256:{{ .Values.collector.image.digest }}"
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -Xdump:what -Xdump:java+system+snap:events=user -Xdump:directory=/tmp/dumps -XX:+HeapDumpOnOutOfMemoryError"
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - MKNOD
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: eventstreams
              mountPath: /etc/eventstreams
      volumes:
      - name: eventstreams
        secret:
          secretName: eventstreams-cluster-operator
          # Secret created by the init-container
          # optional so as to not block startup
          optional: true
    {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  strategy:
    type: Recreate
