apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
    name: quickstart
spec:
    licenseAccept: false
    version: 2020.1.1
    adminApi: {}
    adminUI: {}
    collector: {}
    restProducer: {}
    replicator: {}
    schemaRegistry:
        storage:
            type: ephemeral
    strimziOverrides:
        kafka:
            replicas: 1
            config:
                interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
                offsets.topic.replication.factor: 1
                transaction.state.log.min.isr: 1
                transaction.state.log.replication.factor: 1
            listeners:
                external:
                    type: route
                plain: {}
                tls: {}
            storage:
                type: ephemeral
            metrics: {}
        zookeeper:
            replicas: 1
            storage:
                type: ephemeral
            metrics: {}
