apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      imagePullSecrets:
        - name: ibm-entitlement-key
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-amd64:2020-01-13-23.50.11-7bef612
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                2.4.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                2.4.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
              value: |
                2.4.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |
                2.4.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-amd64:2020-01-13-23.50.11-7bef612
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: strimzi/kafka-bridge:latest
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_IMAGE_PULL_SECRETS
              value: ibm-entitlement-key
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
  strategy:
    type: Recreate
