###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
###############################################################################
############################# IBM EVENT STREAMS ###############################
###############################################################################

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: false
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
nodeSelector: {}
imagePullSecrets: ibm-entitlement-key
operatorIndex:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-catalog
    tag: 2020-05-27-20.18.23-dddcbaf
    digest: e94005266418e74721e00c4118b6552c1bddbca82dc2b871a0051aea88a14fa2
operatorBundle:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator-bundle
    tag: 2020-05-27-20.18.23-dddcbaf
    digest: 89ea3a219f864b40cb89cb3c65070ce583d011ee57ec7971429c89cb7b02e4a0
operator:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-05-30-17.04.53-8dd7640
    digest: a4e4d930f59cd26d7f6a46eabff571af6f85fe6877d62f411555e4948914a68f
operatorInit:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator-init
    tag: 2020-05-30-17.04.53-8dd7640
    digest: 14b5f1e6ec31c6ffd64d17964177f8fa3431287216493ae6878da27384cbf3df
restProducer:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-rest-producer
    tag: 2020-05-29-17.14.21-0ad1614
    digest: 1d205b3022aa6fb199cb00be5fbaa36ae8d23cb6c8518119fdc573311cf7415d
adminApi:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-admin
    tag: 2020-05-29-17.14.24-0ad1614
    digest: 00280349a964b2d74dbabe4bb5704a2a34ba406d2913e9192168e94a3ca3bba0
schemaRegistry:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-registry
    tag: 2020-05-28-16.03.46-a2ca6bf-dev
    digest: 79072605a6eb4cacdd099108536484ac6a8270cc464162f0a4997f4505785c02
schemaRegistryAvro:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-registry-avro
    tag: 2020-05-28-15.51.55-078165d-dev
    digest: cb474d7c2434e3fb7a7092239d5fe43095a4793e1daca0f21adff6c311a0a43e
schemaRegistryProxy:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-proxy
    tag: 2020-05-29-17.14.19-0ad1614
    digest: f4d2f3885a8226e4bdaa7f93b1b8ce2a5591e3b2d03388eb2b56c4e51f14261f
adminUi:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-admin-ui
    tag: 2020-05-29-16.49.24-2218a80-dev
    digest: 699d9858950d5d8c1461d9a00a5e8e0fc0970619afd1484b40eecdfa46610172
adminUiDatabase:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-session-store
    tag: 2020-04-09-15.40.36-f32e234
    digest: 63bbdfe2e4ffc6442346fb59212b436191338fdace7de0bb909cdfd95c823518
collector:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-metrics-collector
    tag: 2020-05-28-16.23.09-8cee6ad
    digest: 91e9ce93c30e9a72fbef1968c325bdfbf9bc44a17a026fc8cbcd0a5079ac1071
zookeeper:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
kafka:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
kafkaConnect:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
kafkaConnects2i:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
cruiseControl:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
topicOperator:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-05-30-17.04.53-8dd7640
    digest: a4e4d930f59cd26d7f6a46eabff571af6f85fe6877d62f411555e4948914a68f
userOperator:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-05-30-17.04.53-8dd7640
    digest: a4e4d930f59cd26d7f6a46eabff571af6f85fe6877d62f411555e4948914a68f
kafkaInit:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-05-30-17.04.53-8dd7640
    digest: a4e4d930f59cd26d7f6a46eabff571af6f85fe6877d62f411555e4948914a68f
tlsSidecarZookeeper:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
tlsSidecarKafka:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
tlsSidecarEntityOperator:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
tlsSidecarCruiseControl:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
kafkaMirrorMaker:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
kafkaExporter:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
jmxTrans:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-jmxtrans
    tag: 2020-05-30-17.04.53-8dd7640
    digest: 1508a8bb919328db7b4de44a698c89b45af0ff06b1c8d56052f5a86fb56eb323
kafkaMirrorMaker2:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-05-30-17.04.53-8dd7640
    digest: a8af70a33c4dc8c2d3db5f4bba893f8abda67fffa5c339de42d161b9bdb5f0e5
resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 1Gi
    cpu: 200m
livenessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
readinessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
createGlobalResources: true
