###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
###############################################################################
############################# IBM EVENT STREAMS ###############################
###############################################################################

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: false
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
nodeSelector: {}
imagePullSecrets: ibm-entitlement-key
operator:
  image:
    repository: docker.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-05-10.37.08-0ac9331
    digest: 04bbdd32d1a5dc12e9554ccd786cd1ff78b9c5eb6d6fea84aa459806ccd62e9a
operatorInit:
  image:
    repository: docker.io
    name: ibmcom/ibm-eventstreams-operator-init
    tag: 2020-06-05-10.37.08-0ac9331
    digest: 20bd6430cfc069b2131889e4e331fe321ea1ff90d5e0308d420d386379e0cb14
restProducer:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-rest-producer
    tag: 2020-06-05-13.21.11-c702b9a
    digest: 6907cf1caabac4ce792527b741cdfca9bad242d82e38872ef1bf3d6eb8090eb1
adminApi:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-admin
    tag: 2020-06-05-13.21.19-c702b9a
    digest: a2d4323b0004f8dd1c08bfb14d08d096990174c81e02bcf8b09149156db14007
schemaRegistry:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-registry
    tag: 2020-06-05-14.46.24-a2ca6bf
    digest: eb5cc69eedc6a212f461dc1821441e30c25ed485cf8b659570447765628e1510
schemaRegistryAvro:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-registry-avro
    tag: 2020-06-05-10.51.40-1f4dcf7
    digest: 95430d8b98b401b8fd37f8c2f093e9f77dd48b6ae02b7e9b061891ad6657fe34
schemaRegistryProxy:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-proxy
    tag: 2020-06-05-13.21.10-c702b9a
    digest: bff1a3ef454ce760b29e760c258f4d7bedac42926f4c9e078593ebc90cb6962a
adminUi:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-admin-ui
    tag: 2020-06-05-10.52.17-0b6f288
    digest: ac2f26f56dccf7173085bb787b325f2167919a70f8803f18bc8cb572e90b30e3
adminUiDatabase:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-session-store
    tag: 2020-06-05-11.16.07-f32e234
    digest: 83986e67b9b9863201cc6754d8757d67712c2e20eb74ece2afe62928687d7a70
collector:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-metrics-collector
    tag: 2020-06-05-11.14.00-b99fe20
    digest: 104a31f46b2a198968717d2524169c1d814c22a83049386d85c3bef2475bf026
zookeeper:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
kafka:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
kafkaConnect:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
kafkaConnects2i:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
cruiseControl:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
topicOperator:
  image:
    repository: docker.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-05-10.37.08-0ac9331
    digest: 04bbdd32d1a5dc12e9554ccd786cd1ff78b9c5eb6d6fea84aa459806ccd62e9a
userOperator:
  image:
    repository: docker.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-05-10.37.08-0ac9331
    digest: 04bbdd32d1a5dc12e9554ccd786cd1ff78b9c5eb6d6fea84aa459806ccd62e9a
kafkaInit:
  image:
    repository: docker.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-05-10.37.08-0ac9331
    digest: 04bbdd32d1a5dc12e9554ccd786cd1ff78b9c5eb6d6fea84aa459806ccd62e9a
tlsSidecarZookeeper:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
tlsSidecarKafka:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
tlsSidecarEntityOperator:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
tlsSidecarCruiseControl:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
kafkaMirrorMaker:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
kafkaExporter:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
jmxTrans:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-jmxtrans
    tag: 2020-06-05-10.37.08-0ac9331
    digest: 7a431edd8698be570d9236f3621be3f415eb042fe5932d6820a98d6499c57ccb
kafkaMirrorMaker2:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-05-10.37.08-0ac9331
    digest: 65776a558e6f84060895207798792601f96bd53be1226b4727a548757ebb1c57
resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 1Gi
    cpu: 200m
livenessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
readinessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
createGlobalResources: true
