###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
###############################################################################
############################# IBM EVENT STREAMS ###############################
###############################################################################

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: false
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
nodeSelector: {}
imagePullSecrets: ibm-entitlement-key
operatorIndex:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-catalog
    tag: 2020-05-27-20.18.23-dddcbaf
    digest: e94005266418e74721e00c4118b6552c1bddbca82dc2b871a0051aea88a14fa2
operatorBundle:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator-bundle
    tag: 2020-05-27-20.18.23-dddcbaf
    digest: 89ea3a219f864b40cb89cb3c65070ce583d011ee57ec7971429c89cb7b02e4a0
operator:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-01-21.01.21-aef8433
    digest: 09050faececad7d53c644e4324f700abee893640acd50d9b8f0ec7c523e5deba
operatorInit:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator-init
    tag: 2020-06-01-21.01.21-aef8433
    digest: 11989e4a6d40fc373bae0f4999204cdfc367c288989f0d7e4872da0ce57de443
restProducer:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-rest-producer
    tag: 2020-06-01-11.20.11-fb135ce
    digest: cf2e78d822593b7b768a6fbfc790341d208489f421384da9c2167aaf68efed3f
adminApi:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-admin
    tag: 2020-06-01-11.20.11-fb135ce
    digest: 557bdfcba76617f816fc98cbdb8127baf5e2a56e3455aa1bbf7b7b82949085a1
schemaRegistry:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-registry
    tag: 2020-05-28-16.03.46-a2ca6bf-dev
    digest: 79072605a6eb4cacdd099108536484ac6a8270cc464162f0a4997f4505785c02
schemaRegistryAvro:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-registry-avro
    tag: 2020-05-28-15.51.55-078165d-dev
    digest: cb474d7c2434e3fb7a7092239d5fe43095a4793e1daca0f21adff6c311a0a43e
schemaRegistryProxy:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-schema-proxy
    tag: 2020-06-01-11.20.11-fb135ce
    digest: 669c495a1de17b4653616fbe6739f0baf0c44af3ba310998bb6f9d38cb7a4f43
adminUi:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-admin-ui
    tag: 2020-06-01-16.58.01-d26af6f-dev
    digest: 41a62dc48600d0524ef04015be197fd11bd970a234a8f1830734277267b40cd2
adminUiDatabase:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-session-store
    tag: 2020-04-09-15.40.36-f32e234
    digest: 63bbdfe2e4ffc6442346fb59212b436191338fdace7de0bb909cdfd95c823518
collector:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-metrics-collector
    tag: 2020-06-02-09.28.49-9e56b11
    digest: 79ac0a08abc544b2a9523368394661ddd0f74b38d8706e029ebec98cefb50898
zookeeper:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
kafka:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
kafkaConnect:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
kafkaConnects2i:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
cruiseControl:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
topicOperator:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-01-21.01.21-aef8433
    digest: 09050faececad7d53c644e4324f700abee893640acd50d9b8f0ec7c523e5deba
userOperator:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-01-21.01.21-aef8433
    digest: 09050faececad7d53c644e4324f700abee893640acd50d9b8f0ec7c523e5deba
kafkaInit:
  image:
    repository: dockerhub.io
    name: ibmcom/ibm-eventstreams-operator
    tag: 2020-06-01-21.01.21-aef8433
    digest: 09050faececad7d53c644e4324f700abee893640acd50d9b8f0ec7c523e5deba
tlsSidecarZookeeper:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
tlsSidecarKafka:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
tlsSidecarEntityOperator:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
tlsSidecarCruiseControl:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
kafkaMirrorMaker:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
kafkaExporter:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
jmxTrans:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-jmxtrans
    tag: 2020-06-01-21.01.21-aef8433
    digest: 14ae5aa0c589f4ea223a0dee3c5fc47162d170009c896f0f51c2e89d4b4494dc
kafkaMirrorMaker2:
  image:
    repository: cp.icr.io
    name: cp/ibm-eventstreams-kafka
    tagPrefix: 2020-06-01-21.01.21-aef8433
    digest: e9eb1c9cba5256f69fd240b57c7e22b30a80b011a7f157a370d29cc906823cde
resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 1Gi
    cpu: 200m
livenessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
readinessProbe:
  periodSeconds: 10
  initialDelaySeconds: 10
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5
createGlobalResources: true
