FROM registry.access.redhat.com/ubi7/ubi-minimal

RUN microdnf -y update \
    && microdnf -y install hostname openssl tar vi which java-1.8.0-openjdk-headless \
    && microdnf -y clean all

COPY target/eventstreams-cluster-operator-0.0.1.jar /eventstreams-cluster-operator.jar
COPY target/lib /lib

ENV JAVA_MAIN=com.ibm.eventstreams.Main
ENV JAVA_CLASSPATH=/eventstreams-cluster-operator.jar:/lib/*

CMD java -classpath ${JAVA_CLASSPATH} ${JAVA_MAIN}
