apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
    app.kubernetes.io/instance: eventstreams-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: eventstreams-operator
