apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-cluster-operator-namespaced
  labels:
    app: eventstreams
rules:
- apiGroups:
  - ""
  resources:
  # The cluster operator needs to access and manage service accounts to grant Strimzi components cluster permissions
  - serviceaccounts
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  # The cluster operator needs to access and manage rolebindings to grant Strimzi components cluster permissions
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  # The cluster operator needs to access and manage config maps for Strimzi components configuration
  - configmaps
  # The cluster operator needs to access and manage services to expose Strimzi components to network traffic
  - services
  # The cluster operator needs to access and manage secrets to handle credentials
  - secrets
  # The cluster operator needs to access and manage persistent volume claims to bind them to Strimzi components for persistent data
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "eventstreams.ibm.com"
  resources:
  # The cluster operator runs the KafkaAssemblyOperator, which needs to access and manage Kafka resources
  - kafkas
  - kafkas/status
  # The cluster operator runs the KafkaConnectAssemblyOperator, which needs to access and manage KafkaConnect resources
  - kafkaconnects
  - kafkaconnects/status
  # The cluster operator runs the KafkaConnectS2IAssemblyOperator, which needs to access and manage KafkaConnectS2I resources
  - kafkaconnects2is
  - kafkaconnects2is/status
  # The cluster operator runs the KafkaConnectorAssemblyOperator, which needs to access and manage KafkaConnector resources
  - kafkaconnectors
  - kafkaconnectors/status
  # The cluster operator runs the KafkaMirrorMakerAssemblyOperator, which needs to access and manage KafkaMirrorMaker resources
  - kafkamirrormakers
  - kafkamirrormakers/status
  # The cluster operator runs the KafkaBridgeAssemblyOperator, which needs to access and manage BridgeMaker resources
  - kafkabridges
  - kafkabridges/status
  # The cluster operator runs the KafkaMirrorMaker2AssemblyOperator, which needs to access and manage KafkaMirrorMaker2 resources
  - kafkamirrormaker2s
  - kafkamirrormaker2s/status
  # The cluster operator runs the KafkaRebalanceAssemblyOperator, which needs to access and manage KafkaRebalance resources
  - kafkarebalances
  - kafkarebalances/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  # The cluster operator needs to access and delete pods, this is to allow it to monitor pod health and coordinate rolling updates
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  # The cluster operator needs the extensions api as the operator supports Kubernetes version 1.11+
  # apps/v1 was introduced in Kubernetes 1.14
  - "extensions"
  resources:
  # The cluster operator needs to access and manage deployments to run deployment based Strimzi components
  - deployments
  - deployments/scale
  # The cluster operator needs to access replica sets to manage Strimzi components and to determine error states
  - replicasets
  # The cluster operator needs to access and manage replication controllers to manage replicasets
  - replicationcontrollers
  # The cluster operator needs to access and manage network policies to lock down communication between Strimzi components
  - networkpolicies
  # The cluster operator needs to access and manage ingresses which allow external access to the services in a cluster
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "apps"
  resources:
  # The cluster operator needs to access and manage deployments to run deployment based Strimzi components
  - deployments
  - deployments/scale
  - deployments/status
  # The cluster operator needs to access and manage stateful sets to run stateful sets based Strimzi components
  - statefulsets
  # The cluster operator needs to access replica-sets to manage Strimzi components and to determine error states
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  # The cluster operator needs to be able to create events and delegate permissions to do so
  - events
  verbs:
  - create
- apiGroups:
  # OpenShift S2I requirements
  - apps.openshift.io
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  - deploymentconfigs/status
  - deploymentconfigs/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  # OpenShift S2I requirements
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update
- apiGroups:
  # OpenShift S2I requirements
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreams/status
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  # The cluster operator needs to access and manage network policies to lock down communication between Strimzi components
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  # The cluster operator needs to access and manage routes to expose Strimzi components for external access
  - routes
  - routes/custom-host
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
- apiGroups:
  - policy
  resources:
  # The cluster operator needs to access and manage pod disruption budgets this limits the number of concurrent disruptions
  # that a Strimzi component experiences, allowing for higher availability
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  # The Event Streams Operator requires the "get" and "list" permissions for namespaces
  # This is to allow the operator to query the namespaces in the cluster and watch all that it can see when
  # WATCHED_NAMESPACES has the value '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  # The Event Streams Operator requires the "get" and "list" permissions for nodes
  # This is to allow the operator to label Kafka brokers in a rack-aware installation
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
- apiGroups:
  - ""
  # The Event Streams Operator requires the "patch" permissions for pods
  # This is to allow the operator to delegate the same permissions to the Admin API

  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for validatingwebhookconfigurations
  # This is to allow the operator to create and manage validation webhooks required for an Event Streams custom resources to
  # be validated prior to application to the Kubernetes server
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  # The Event Streams Operator requires the "get", "list", "create" and "patch" permissions for clusterroles and clusterrolebindings
  # This is to allow the operator to create and manage rolebindings that bind to clusterroles required for components of Event Streams
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - console.openshift.io
  # The Event Streams Operator requires the "get", "create", "delete" and "patch" permissions for consoleyamlsamples
  # This is to allow the operator to create and manage Event Streams sample yamls for use by OLM
  resources:
  - consoleyamlsamples
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - monitoring.coreos.com
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for servicemonitors
  # This is to allow the operator to create and manage the resources required for an Event Streams instance
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - eventstreams.ibm.com
  # The Event Streams Operator requires the "*" permissions for eventstreams, eventstreamsgeoreplicator and kafkausers
  # This is to allow the operator to create and manage the resources required for an Event Streams and Event Streams geo-replicator instance
  resources:
  - "eventstreams"
  - "eventstreams/status"
  - "eventstreamsgeoreplicators"
  - "eventstreamsgeoreplicators/status"
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "oidc.security.ibm.com"
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for oidc clients
  # This is to allow the operator to create and manage an oidc client request required for authentication in Event Streams
  resources:
  - clients
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - "cp4i.ibm.com"
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for oidc clients
  # This is to allow the operator to create and manage an oidc client request required for authentication in Event Streams
  resources:
  - cp4iservicesbindings
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - "operator.ibm.com"
  resources:
  - operandrequests
  verbs:
  - get
  - list
  - create
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for custom resource definitions
  # This is to allow the operator to query the kubernetes server for whether certain CRDs are present
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
