apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-cluster-operator-namespaced
  labels:
    app: eventstreams
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "eventstreams.ibm.com"
  resources:
  # The cluster operator runs the KafkaAssemblyOperator, which needs to access Kafka resources
  - kafkas
  - kafkas/status
  # The cluster operator runs the KafkaConnectAssemblyOperator, which needs to access KafkaConnect resources
  - kafkaconnects
  - kafkaconnects/status
  # The cluster operator runs the KafkaConnectS2IAssemblyOperator, which needs to access KafkaConnectS2I resources
  - kafkaconnects2is
  - kafkaconnects2is/status
  # The cluster operator runs the KafkaConnectorAssemblyOperator, which needs to access KafkaConnector resources
  - kafkaconnectors
  - kafkaconnectors/status
  # The cluster operator runs the KafkaMirrorMakerAssemblyOperator, which needs to access KafkaMirrorMaker resources
  - kafkamirrormakers
  - kafkamirrormakers/status
  # The cluster operator runs the KafkaBridgeAssemblyOperator, which needs to access BridgeMaker resources
  - kafkabridges
  - kafkabridges/status
  # The cluster operator runs the KafkaMirrorMaker2AssemblyOperator, which needs to access KafkaMirrorMaker2 resources
  - kafkamirrormaker2s
  - kafkamirrormaker2s/status
  # The cluster operator runs the KafkaRebalanceAssemblyOperator, which needs to access KafkaRebalance resources
  - kafkarebalances
  - kafkarebalances/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - deployments
  - deployments/scale
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments
  - deployments/scale
  - deployments/status
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups: # OpenShift S2I requirements
  - "extensions"
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  - deploymentconfigs/scale
  - deploymentconfigs/status
  - deploymentconfigs/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
  - update
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreams/status
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  # The Event Streams Operator requires the "get" and "list" permissions for namespaces
  # This is to allow the operator to query the namespaces in the cluster and watch all that it can see when
  # WATCHED_NAMESPACES has the value '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  # The Event Streams Operator requires the "patch" permissions for pods
  # This is to allow the operator to delegate the same permissions to the Admin API

  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for validatingwebhookconfigurations
  # This is to allow the operator to create and manage validation webhooks required for an Event Streams custom resources to
  # be validated prior to application to the Kubernetes server
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  # The Event Streams Operator requires the "get" and "list" permissions for clusterroles and clusterrolebindings
  # This is to allow the operator to create and manage rolebindings that bind to clusterroles required for components of Event Streams
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
- apiGroups:
  - console.openshift.io
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for consoleyamlsamples
  # This is to allow the operator to create and manage Event Streams sample yamls for use by OLM
  resources:
  - consoleyamlsamples
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - monitoring.coreos.com
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for servicemonitors
  # This is to allow the operator to create and manage the resources required for an Event Streams instance
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - eventstreams.ibm.com
  # The Event Streams Operator requires the "*" permissions for eventstreams, eventstreamsgeoreplicator and kafkausers
  # This is to allow the operator to create and manage the resources required for an Event Streams and Event Streams geo-replicator instance
  resources:
  - "eventstreams"
  - "eventstreams/status"
  - "eventstreamsgeoreplicators"
  - "eventstreamsgeoreplicators/status"
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - "oidc.security.ibm.com"
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for oidc clients
  # This is to allow the operator to create and manage an oidc client request required for authentication in Event Streams
  resources:
  - clients
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - "cp4i.ibm.com"
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for oidc clients
  # This is to allow the operator to create and manage an oidc client request required for authentication in Event Streams
  resources:
  - cp4iservicesbindings
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for custom resource definitions
  # This is to allow the operator to query the kubernetes server for whether certain CRDs are present
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
