##---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
subjects:
- kind: ServiceAccount
  name: eventstreams-cluster-operator
  namespace: myproject
roleRef:
  kind: ClusterRole
  name: eventstreams-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
