apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-cluster-operator-global
  labels:
    app: eventstreams
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  # Persistent Volumes can be resized only when it is supported in the storage class.
  # Therefore we need the ability to get the storage class details and we require this access right.
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  # The listing of nodes is needed to find the node addresses when the NodePort access is configured and set the proper
  # addresses in the status
  - list
- apiGroups:
  - admissionregistration.k8s.io
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for validatingwebhookconfigurations
  # This is to allow the operator to create and manage validation webhooks required for an Event Streams custom resources to
  # be validated prior to application to the Kubernetes server
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  # The Event Streams Operator requires the "get" and "list" permissions for clusterroles and clusterrolebindings
  # This is to allow the operator to query the Kubernetes server for whether the required cluster roles and bindings are present
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
- apiGroups:
  - console.openshift.io
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for consoleyamlsamples
  # This is to allow the operator to setup samples for the OLM UI
  resources:
  - consoleyamlsamples
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for custom resource definitions
  # This is to allow the operator to query the kubernetes server for whether certain CRDs are present
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
