apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-cluster-operator-global
  labels:
    app: eventstreams
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  # The cluster operator needs to create and manage cluster role bindings in the case of an install where a user
  # has specified they want their cluster role bindings generated
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  # The cluster operator requires "get" permissions to view storage class details
  # This is because only a persistent volume of a supported storage class type can be resized
  - storageclasses
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  # The cluster operator requires "list" permissions to view all nodes in a cluster
  # The listing is used to determine the node addresses when NodePort access is configured
  # These addresses are then exposed in the custom resource states
  - nodes
  verbs:
  - list
- apiGroups:
  - admissionregistration.k8s.io
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for validatingwebhookconfigurations
  # This is to allow the operator to create and manage validation webhooks required for an Event Streams custom resources to
  # be validated prior to application to the Kubernetes server
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  # The Event Streams Operator requires the "get" and "list" permissions for clusterroles and clusterrolebindings
  # This is to allow the operator to query the Kubernetes server for whether the required cluster roles and bindings are present
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
- apiGroups:
  - console.openshift.io
  # The Event Streams Operator requires the "get", "create", "patch" and "delete" permissions for consoleyamlsamples
  # This is to allow the operator to setup samples for the OLM UI
  resources:
  - consoleyamlsamples
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  # The Event Streams Operator requires the "get", "create" and "patch" permissions for custom resource definitions
  # This is to allow the operator to query the kubernetes server for whether certain CRDs are present
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
