##---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-kafka-broker
  labels:
    app: eventstreams
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
