apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreams-ui-clusterrole
  labels:
    app: eventstreams
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
