##---
###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2019  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: eventstreams-admin-clusterrole
  labels:
    app: eventstreams
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - list
  - get
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - list
