###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
    app.kubernetes.io/instance: eventstreams-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: eventstreams-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eventstreams-cluster-operator
      eventstreams.ibm.com/kind: cluster-operator
  template:
    metadata:
      annotations:
        productID: "2cba508800504d0abfa48a0e2c4ecbe2"
        productName: "IBM Event Streams"
        productVersion: "10.0.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        name: eventstreams-cluster-operator
        eventstreams.ibm.com/kind: cluster-operator
        app: eventstreams
        app.kubernetes.io/instance: eventstreams-operator
        app.kubernetes.io/managed-by: olm
        app.kubernetes.io/name: eventstreams-operator
    spec:
      serviceAccountName: eventstreams-cluster-operator
      initContainers:
      - name: init
        image: dockerhub.io/ibmcom/ibm-eventstreams-operator-init@sha256:287613939e115a00b8f1531d58d1d6774ff8678f889b1f06f0a946c88514f802
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      containers:
      - name: eventstreams-cluster-operator
        image: dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:6bf4e4b5d425efaddd85f111cae70dfd7eafe12f33db37c58a0f68ae82c8c6aa
        args:
        - /opt/strimzi/bin/eventstreams_cluster_operator_run.sh
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EVENTSTREAMS_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: EVENTSTREAMS_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: EVENTSTREAMS_IMAGE_PULL_SECRETS
          value: ibm-entitlement-key
        - name: EVENTSTREAMS_LOG_LEVEL
          value: "INFO"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          # Core images

          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_DEFAULT_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_KAFKA_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_KAFKA_CONNECT_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:6266d5f4996bf10a7c59902f155f643a28b8f7f1a38c5ecf885e4d5d27f4081a
        - name: EVENTSTREAMS_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: "dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:6bf4e4b5d425efaddd85f111cae70dfd7eafe12f33db37c58a0f68ae82c8c6aa"
        - name: EVENTSTREAMS_DEFAULT_USER_OPERATOR_IMAGE
          value: "dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:6bf4e4b5d425efaddd85f111cae70dfd7eafe12f33db37c58a0f68ae82c8c6aa"
        - name: EVENTSTREAMS_DEFAULT_KAFKA_INIT_IMAGE
          value: "dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:6bf4e4b5d425efaddd85f111cae70dfd7eafe12f33db37c58a0f68ae82c8c6aa"
        - name: EVENTSTREAMS_DEFAULT_JMXTRANS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-jmxtrans@sha256:5470c2e525dab133bd60b2ebef2f6af7af5a17208f7bd951ae99982e7b5a46ce"
        - name: EVENTSTREAMS_DEFAULT_REST_PRODUCER_IMAGE # Proprietary images
          value: "cp.icr.io/cp/ibm-eventstreams-rest-producer@sha256:cf2e78d822593b7b768a6fbfc790341d208489f421384da9c2167aaf68efed3f"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_API_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin@sha256:557bdfcba76617f816fc98cbdb8127baf5e2a56e3455aa1bbf7b7b82949085a1"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry@sha256:79072605a6eb4cacdd099108536484ac6a8270cc464162f0a4997f4505785c02"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_AVRO_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry-avro@sha256:cb474d7c2434e3fb7a7092239d5fe43095a4793e1daca0f21adff6c311a0a43e"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_PROXY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-proxy@sha256:669c495a1de17b4653616fbe6739f0baf0c44af3ba310998bb6f9d38cb7a4f43"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin-ui@sha256:41a62dc48600d0524ef04015be197fd11bd970a234a8f1830734277267b40cd2"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_REDIS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-session-store@sha256:63bbdfe2e4ffc6442346fb59212b436191338fdace7de0bb909cdfd95c823518"
        - name: EVENTSTREAMS_DEFAULT_COLLECTOR_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-metrics-collector@sha256:91e9ce93c30e9a72fbef1968c325bdfbf9bc44a17a026fc8cbcd0a5079ac1071"
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -Xdump:what -Xdump:java+system+snap:events=user
            -Xdump:directory=/tmp/dumps -XX:+HeapDumpOnOutOfMemoryError"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - MKNOD
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: eventstreams
          mountPath: /etc/eventstreams
      volumes:
      - name: eventstreams
        secret:
          secretName: eventstreams-cluster-operator
          # Secret created by the init-container
          # optional so as to not block startup
          optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
  strategy:
    type: Recreate
