###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2019  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eventstreams-cluster-operator
      eventstreams.ibm.com/kind: cluster-operator
  template:
    metadata:
      annotations:
        cloudpakId: c8b82d189e7545f0892db9ef2731b90d
        cloudpakName: IBM Cloud Pak for Integration
        cloudpakVersion: 2019.4.1
        productChargedContainers: ""
        productCloudpakRatio: "1:1"
        productID: ID
        productMetric: VIRTUAL_PROCESSOR_CORE
        productName: eventstreams
        productVersion: version
        prometheus.io/port: "8080"
        prometheus.io/scheme: https
        prometheus.io/scrape: "true"
      labels:
        name: eventstreams-cluster-operator
        eventstreams.ibm.com/kind: cluster-operator
        app: eventstreams
    spec:
      imagePullSecrets:
      - name: ibm-entitlement-key
      serviceAccountName: eventstreams-cluster-operator
      initContainers:
      - name: install-validating-webhook
        image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-init:latest
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      containers:
      - name: eventstreams-cluster-operator
        image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator:latest
        args:
        - /opt/strimzi/bin/eventstreams_cluster_operator_run.sh
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_IMAGE_PULL_POLICY
          value: Always
        - name: EVENTSTREAMS_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: EVENTSTREAMS_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: EVENTSTREAMS_IMAGE_PULL_SECRETS
          value: ibm-entitlement-key
        - name: EVENTSTREAMS_LOG_LEVEL
          value: "INFO"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          # Core images

          value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_DEFAULT_CRUISE_CONTROL_IMAGE
          value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
          value: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_KAFKA_IMAGES
          value: |
            2.5.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_KAFKA_CONNECT_IMAGES
          value: |
            2.5.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.5.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.5.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            2.5.0=hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka:latest-kafka-2.5.0
        - name: EVENTSTREAMS_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator:latest"
        - name: EVENTSTREAMS_DEFAULT_USER_OPERATOR_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator:latest"
        - name: EVENTSTREAMS_DEFAULT_KAFKA_INIT_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator:latest"
        - name: EVENTSTREAMS_DEFAULT_JMXTRANS_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/jmxtrans:latest"
        - name: EVENTSTREAMS_DEFAULT_REST_PRODUCER_IMAGE # Proprietary images
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-rest-producer-v2-icp-linux:2020-05-05-13.48.10-d389015"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_API_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-admin-icp-linux:2020-05-11-18.27.50-d9d5c3a"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-schema-registry-icp-linux:2020-05-01-09.46.24-21cd0a7-dev"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_AVRO_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-schema-registry-avro-icp-linux:2020-04-09-16.03.17-cd87238"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_PROXY_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/evenstreams-schema-proxy-icp-linux:2020-05-11-12.38.26-d1887e4"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-admin-ui-icp-linux:2020-05-01-14.45.21-4ffc2c8-dev"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_REDIS_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-session-store-icp-linux:2020-04-09-15.40.36-f32e234"
        - name: EVENTSTREAMS_DEFAULT_COLLECTOR_IMAGE
          value: "hyc-qp-stable-docker-local.artifactory.swg-devops.com/eventstreams-metrics-collector-icp-linux:2020-04-08-11.08.41-3cb71d9"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - MKNOD
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: eventstreams
          mountPath: /etc/eventstreams
      volumes:
      - name: eventstreams
        secret:
          secretName: eventstreams-cluster-operator
          # Secret created by the init-container
          # optional so as to not block startup
          optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
  strategy:
    type: Recreate
