###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
    app.kubernetes.io/instance: eventstreams-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: eventstreams-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eventstreams-cluster-operator
      eventstreams.ibm.com/kind: cluster-operator
  template:
    metadata:
      annotations:
        productID: "2cba508800504d0abfa48a0e2c4ecbe2"
        productName: "IBM Event Streams"
        productVersion: "10.0.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: ""
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        name: eventstreams-cluster-operator
        eventstreams.ibm.com/kind: cluster-operator
        app: eventstreams
        app.kubernetes.io/instance: eventstreams-operator
        app.kubernetes.io/managed-by: olm
        app.kubernetes.io/name: eventstreams-operator
    spec:
      serviceAccountName: eventstreams-cluster-operator
      initContainers:
      - name: init
        image: docker.io/ibmcom/ibm-eventstreams-operator-init@sha256:227918419cd715ed97ad14475a0b3abcca7112e197ac339a722450ee3bbc3d53
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      containers:
      - name: eventstreams-cluster-operator
        image: docker.io/ibmcom/ibm-eventstreams-operator@sha256:283a4298688ca201fa6b4fbc261a936c8afacb0052424403522f0b5fa2ccbf49
        args:
        - /opt/strimzi/bin/eventstreams_cluster_operator_run.sh
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EVENTSTREAMS_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: EVENTSTREAMS_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: EVENTSTREAMS_IMAGE_PULL_SECRETS
          value: ibm-entitlement-key
        - name: EVENTSTREAMS_LOG_LEVEL
          value: "INFO"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          # Core images

          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_DEFAULT_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_KAFKA_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_KAFKA_CONNECT_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:bc985ce30c4ea306ea8385510fd9cc0ed60f415c9dbedf18e16fd4bb27697083
        - name: EVENTSTREAMS_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: "docker.io/ibmcom/ibm-eventstreams-operator@sha256:283a4298688ca201fa6b4fbc261a936c8afacb0052424403522f0b5fa2ccbf49"
        - name: EVENTSTREAMS_DEFAULT_USER_OPERATOR_IMAGE
          value: "docker.io/ibmcom/ibm-eventstreams-operator@sha256:283a4298688ca201fa6b4fbc261a936c8afacb0052424403522f0b5fa2ccbf49"
        - name: EVENTSTREAMS_DEFAULT_KAFKA_INIT_IMAGE
          value: "docker.io/ibmcom/ibm-eventstreams-operator@sha256:283a4298688ca201fa6b4fbc261a936c8afacb0052424403522f0b5fa2ccbf49"
        - name: EVENTSTREAMS_DEFAULT_JMXTRANS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-jmxtrans@sha256:f5924ae3da849f47d28f6a7396a2f4137e440f7d6b6e176408fed322b119447a"
        - name: EVENTSTREAMS_DEFAULT_REST_PRODUCER_IMAGE # Proprietary images
          value: "cp.icr.io/cp/ibm-eventstreams-rest-producer@sha256:1a4236d0aeaaba181d4d12a274fc449d01a65223ea356b83a8ffd166dd8231e0"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_API_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin@sha256:0eda65ae97f016674c68da4c48e8521e4969241d1a8c6eea1278266f1ac032c2"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry@sha256:a9480b708ad67fee6f6f52298bd5b3f6030a2a231fe543d75ddb71b3af9ec009"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_AVRO_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry-avro@sha256:e2d2723a3f9b595da423e37d84e159a3e1f8f7a3bb2106cc4fbd377e0f620e98"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_PROXY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-proxy@sha256:6cfbbec3680c8cc57ec6213de46fe68ef9c75f13ad4f274b9cd13eecea8861c1"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin-ui@sha256:8e202916e2153974a3d95b2aca206a5064d8c726eee89b5c6dc418791954a212"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_REDIS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-session-store@sha256:88ac33a06800a94d3a44c86960c6f75918edafd3896517520cacfcbf0c29ee5d"
        - name: EVENTSTREAMS_DEFAULT_COLLECTOR_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-metrics-collector@sha256:b9e2c6820ba10585e32111c4c4038df53fece0f1d43859817be633d1bc26b7fe"
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -Xdump:what -Xdump:java+system+snap:events=user
            -Xdump:directory=/tmp/dumps -XX:+HeapDumpOnOutOfMemoryError"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - MKNOD
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: eventstreams
          mountPath: /etc/eventstreams
      volumes:
      - name: eventstreams
        secret:
          secretName: eventstreams-cluster-operator
          # Secret created by the init-container
          # optional so as to not block startup
          optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
  strategy:
    type: Recreate
