###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2019  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
    app.kubernetes.io/instance: eventstreams-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: eventstreams-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eventstreams-cluster-operator
      eventstreams.ibm.com/kind: cluster-operator
  template:
    metadata:
      annotations:
        productID: "2cba508800504d0abfa48a0e2c4ecbe2"
        productName: "IBM Event Streams"
        productVersion: "10.0.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        name: eventstreams-cluster-operator
        eventstreams.ibm.com/kind: cluster-operator
        app: eventstreams
        app.kubernetes.io/instance: eventstreams-operator
        app.kubernetes.io/managed-by: olm
        app.kubernetes.io/name: eventstreams-operator
    spec:
      serviceAccountName: eventstreams-cluster-operator
      initContainers:
      - name: init
        image: dockerhub.io/ibmcom/ibm-eventstreams-operator-init@sha256:5e56fac6ea864b51dfea9621674a3d379d280953c46a921c70dfdb77f0062395
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      containers:
      - name: eventstreams-cluster-operator
        image: dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:a7b79921cb79660dcb7bbb96485b7c4b30c2bec73a8f702f087cd714da4aa56e
        args:
        - /opt/strimzi/bin/eventstreams_cluster_operator_run.sh
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EVENTSTREAMS_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: EVENTSTREAMS_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: EVENTSTREAMS_IMAGE_PULL_SECRETS
          value: ibm-entitlement-key
        - name: EVENTSTREAMS_LOG_LEVEL
          value: "INFO"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          # Core images

          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_DEFAULT_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_KAFKA_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_KAFKA_CONNECT_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:0afde4415c69a2bcc1ce983d2d43ecdca4ab0c97a430fe1eeb7ab568235f5777
        - name: EVENTSTREAMS_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: "dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:a7b79921cb79660dcb7bbb96485b7c4b30c2bec73a8f702f087cd714da4aa56e"
        - name: EVENTSTREAMS_DEFAULT_USER_OPERATOR_IMAGE
          value: "dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:a7b79921cb79660dcb7bbb96485b7c4b30c2bec73a8f702f087cd714da4aa56e"
        - name: EVENTSTREAMS_DEFAULT_KAFKA_INIT_IMAGE
          value: "dockerhub.io/ibmcom/ibm-eventstreams-operator@sha256:a7b79921cb79660dcb7bbb96485b7c4b30c2bec73a8f702f087cd714da4aa56e"
        - name: EVENTSTREAMS_DEFAULT_JMXTRANS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-jmxtrans@sha256:83ae01109bdc04a494f0ad1f2811690d92b69311cc01311698174e7653980809"
        - name: EVENTSTREAMS_DEFAULT_REST_PRODUCER_IMAGE # Proprietary images
          value: "cp.icr.io/cp/ibm-eventstreams-rest-producer@sha256:b70a886767179b61401741edffe17ffb757c6cfb9ff7fb147ae848bd741a742e"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_API_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin@sha256:3dda0f71764eb4aa6821144b37d0f522e2949a658537dfcc44fad6eb9b4d690c"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry@sha256:79072605a6eb4cacdd099108536484ac6a8270cc464162f0a4997f4505785c02"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_AVRO_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry-avro@sha256:cb474d7c2434e3fb7a7092239d5fe43095a4793e1daca0f21adff6c311a0a43e"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_PROXY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-proxy@sha256:5579bc8f5d362d759f9736999f6aa78e0fa66a841b05f1aef3f7ed5b79986e9d"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin-ui@sha256:63f450c4fe1149a45415a22578c9e3574a8390589d82e7ea938d1aac3894cb7b"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_REDIS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-session-store@sha256:63bbdfe2e4ffc6442346fb59212b436191338fdace7de0bb909cdfd95c823518"
        - name: EVENTSTREAMS_DEFAULT_COLLECTOR_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-metrics-collector@sha256:91e9ce93c30e9a72fbef1968c325bdfbf9bc44a17a026fc8cbcd0a5079ac1071"
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -Xdump:what -Xdump:java+system+snap:events=user
            -Xdump:directory=/tmp/dumps -XX:+HeapDumpOnOutOfMemoryError"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - MKNOD
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: eventstreams
          mountPath: /etc/eventstreams
      volumes:
      - name: eventstreams
        secret:
          secretName: eventstreams-cluster-operator
          # Secret created by the init-container
          # optional so as to not block startup
          optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
  strategy:
    type: Recreate
