###############################################################################
#
# Licensed Materials - Property of IBM
#
# 5737-H33
#
# (C) Copyright IBM Corp. 2020  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstreams-cluster-operator
  labels:
    app: eventstreams
    app.kubernetes.io/instance: eventstreams-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: eventstreams-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: eventstreams-cluster-operator
      eventstreams.ibm.com/kind: cluster-operator
  template:
    metadata:
      annotations:
        productID: "2cba508800504d0abfa48a0e2c4ecbe2"
        productName: "IBM Event Streams"
        productVersion: "10.0.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: ""
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        name: eventstreams-cluster-operator
        eventstreams.ibm.com/kind: cluster-operator
        app: eventstreams
        app.kubernetes.io/instance: eventstreams-operator
        app.kubernetes.io/managed-by: olm
        app.kubernetes.io/name: eventstreams-operator
    spec:
      serviceAccountName: eventstreams-cluster-operator
      initContainers:
      - name: init
        image: docker.io/ibmcom/ibm-eventstreams-operator-init@sha256:0d9efd9344703a8b72a622e1fc095ba4eb66df9a912c7e1b8dfe246928dedd24
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      containers:
      - name: eventstreams-cluster-operator
        image: docker.io/ibmcom/ibm-eventstreams-operator@sha256:d18a9a49aa7fdfcf58aa4090b32eb5aa1111ea71770dcf0348e667b84901a300
        args:
        - /opt/strimzi/bin/eventstreams_cluster_operator_run.sh
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENTSTREAMS_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EVENTSTREAMS_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: EVENTSTREAMS_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: EVENTSTREAMS_IMAGE_PULL_SECRETS
          value: ibm-entitlement-key
        - name: EVENTSTREAMS_LOG_LEVEL
          value: "INFO"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          # Core images

          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_DEFAULT_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
          value: cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_KAFKA_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_KAFKA_CONNECT_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            2.5.0=cp.icr.io/cp/ibm-eventstreams-kafka@sha256:779aba0434307c1fc08a9d141bcde1a01ebf73c4eed1c14c95bef3c804dfe7cb
        - name: EVENTSTREAMS_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: "docker.io/ibmcom/ibm-eventstreams-operator@sha256:d18a9a49aa7fdfcf58aa4090b32eb5aa1111ea71770dcf0348e667b84901a300"
        - name: EVENTSTREAMS_DEFAULT_USER_OPERATOR_IMAGE
          value: "docker.io/ibmcom/ibm-eventstreams-operator@sha256:d18a9a49aa7fdfcf58aa4090b32eb5aa1111ea71770dcf0348e667b84901a300"
        - name: EVENTSTREAMS_DEFAULT_KAFKA_INIT_IMAGE
          value: "docker.io/ibmcom/ibm-eventstreams-operator@sha256:d18a9a49aa7fdfcf58aa4090b32eb5aa1111ea71770dcf0348e667b84901a300"
        - name: EVENTSTREAMS_DEFAULT_JMXTRANS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-jmxtrans@sha256:59bf2867646a230e3b4874e9487f363ea5af6537b6901372864e1f84472d20d6"
        - name: EVENTSTREAMS_DEFAULT_REST_PRODUCER_IMAGE # Proprietary images
          value: "cp.icr.io/cp/ibm-eventstreams-rest-producer@sha256:e8817fe7d2dce0d0f5b365fe27c1cf0bd6032c12609c75c3b02655606f4eade3"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_API_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin@sha256:701a8884794c054fd9c808e2a6182073f789c88d6b3ad702b0afe9e7721dadea"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry@sha256:eb5cc69eedc6a212f461dc1821441e30c25ed485cf8b659570447765628e1510"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_AVRO_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-registry-avro@sha256:95430d8b98b401b8fd37f8c2f093e9f77dd48b6ae02b7e9b061891ad6657fe34"
        - name: EVENTSTREAMS_DEFAULT_SCHEMA_REGISTRY_PROXY_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-schema-proxy@sha256:57255ab68077d9d970901e8a665ee6cba5e973403c9b9827adc449e513a90d01"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-admin-ui@sha256:608399328b7ca6a332cf7841859ca6536880cf157f3d01a500d87895a2f1881e"
        - name: EVENTSTREAMS_DEFAULT_ADMIN_UI_REDIS_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-session-store@sha256:83986e67b9b9863201cc6754d8757d67712c2e20eb74ece2afe62928687d7a70"
        - name: EVENTSTREAMS_DEFAULT_COLLECTOR_IMAGE
          value: "cp.icr.io/cp/ibm-eventstreams-metrics-collector@sha256:104a31f46b2a198968717d2524169c1d814c22a83049386d85c3bef2475bf026"
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -Xdump:what -Xdump:java+system+snap:events=user
            -Xdump:directory=/tmp/dumps -XX:+HeapDumpOnOutOfMemoryError"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - MKNOD
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: eventstreams
          mountPath: /etc/eventstreams
      volumes:
      - name: eventstreams
        secret:
          secretName: eventstreams-cluster-operator
          # Secret created by the init-container
          # optional so as to not block startup
          optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
  strategy:
    type: Recreate
